language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
    - python -m pytest